/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    news: News;
    stories: Story;
    programmes: Programme;
    publications: Publication;
    board: Board;
    partners: Partner;
    opportunities: Opportunity;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    news: NewsSelect<false> | NewsSelect<true>;
    stories: StoriesSelect<false> | StoriesSelect<true>;
    programmes: ProgrammesSelect<false> | ProgrammesSelect<true>;
    publications: PublicationsSelect<false> | PublicationsSelect<true>;
    board: BoardSelect<false> | BoardSelect<true>;
    partners: PartnersSelect<false> | PartnersSelect<true>;
    opportunities: OpportunitiesSelect<false> | OpportunitiesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    impact: Impact;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    impact: ImpactSelect<false> | ImpactSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Programme launches, partnerships, project updates, awards.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: number;
  title: string;
  /**
   * The web address for this article, e.g. nutritional-campaign-gakenke. Lower case, words joined by hyphens. Changing it breaks any existing links.
   */
  slug: string;
  date: string;
  /**
   * The language this article is written in.
   */
  language?: ('en' | 'fr') | null;
  /**
   * Shown on the news listing and at the top of the article.
   */
  photo: number | Media;
  /**
   * One or two sentences, shown on the listing card.
   */
  excerpt: string;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Photographs and files. Upload once, use anywhere.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe what is in the picture, for people using a screen reader. E.g. "A woman standing in the shop she runs". Leave out "photo of".
   */
  alt: string;
  /**
   * Photographer or source, if one should be shown.
   */
  credit?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    wide?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Accounts of one family or person, and what changed for them.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stories".
 */
export interface Story {
  id: number;
  title: string;
  /**
   * Web address. Lower case, hyphens.
   */
  slug: string;
  date: string;
  photo: number | Media;
  /**
   * The opening, shown on the carousel and listing.
   */
  excerpt: string;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * What FXB Rwanda runs, where, and for how long.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programmes".
 */
export interface Programme {
  id: number;
  name: string;
  /**
   * Web address. Lower case, hyphens.
   */
  slug: string;
  /**
   * Phasing a programme out removes it from the map and the counts, and moves it to the Phased-out Projects page. Nothing is deleted.
   */
  stage: 'current' | 'phased-out';
  /**
   * Lower numbers appear first. Leave blank to sort by name.
   */
  order?: number | null;
  /**
   * Every district this programme reaches. These drive the map on Who We Are and the district counts across the site.
   */
  districts: (
    | 'Bugesera'
    | 'Burera'
    | 'Gakenke'
    | 'Gasabo'
    | 'Gatsibo'
    | 'Gicumbi'
    | 'Gisagara'
    | 'Huye'
    | 'Kamonyi'
    | 'Karongi'
    | 'Kayonza'
    | 'Kicukiro'
    | 'Kirehe'
    | 'Muhanga'
    | 'Musanze'
    | 'Ngoma'
    | 'Ngororero'
    | 'Nyabihu'
    | 'Nyagatare'
    | 'Nyamagabe'
    | 'Nyamasheke'
    | 'Nyanza'
    | 'Nyarugenge'
    | 'Nyaruguru'
    | 'Rubavu'
    | 'Ruhango'
    | 'Rulindo'
    | 'Rusizi'
    | 'Rutsiro'
    | 'Rwamagana'
  )[];
  /**
   * Used on the programme card and its own page.
   */
  photo?: (number | null) | Media;
  /**
   * One sentence. Opens the programme's page.
   */
  summary?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * What the programme delivers — shown as "What it delivers" on its page.
   */
  components?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  /**
   * e.g. "August 2022 – August 2025", or "Ongoing".
   */
  runs?: string | null;
  /**
   * e.g. USAID.
   */
  funder?: string | null;
  /**
   * Only if the programme has a system of its own, like the Sugira Muryango dashboard. Leave blank otherwise.
   */
  externalUrl?: string | null;
  /**
   * Shows a notice on the programme's page saying the description is being confirmed. Untick once FXB has approved the wording.
   */
  unconfirmed?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Anything with a file to download.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publications".
 */
export interface Publication {
  id: number;
  /**
   * e.g. "2025 Annual Report", or "Q3 2025" for a newsletter.
   */
  title: string;
  slug: string;
  /**
   * Newsletters appear on the Newsletters page. The newest Annual Report is announced in the banner at the top of every page.
   */
  category: 'annual-report' | 'project-report' | 'policy' | 'brochure' | 'newsletter';
  date: string;
  /**
   * The PDF itself. The file size shown on the site is read from it.
   */
  file: number | Media;
  /**
   * Optional cover image. Reports and newsletters normally have one; policy documents normally do not.
   */
  cover?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Board of Directors, in the order they should appear.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "board".
 */
export interface Board {
  id: number;
  /**
   * As it should appear, including any honorific — e.g. "Fr. Pierre Celestin NGOBOKA (PhD)".
   */
  name: string;
  /**
   * e.g. Chairperson.
   */
  role: string;
  /**
   * Lower numbers first. Chairperson is 1.
   */
  order: number;
  /**
   * A square portrait with the background removed. It is shown in a circle, so anything left behind the person will show.
   */
  portrait: number | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * Organisations shown on the partner walls.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: number;
  name: string;
  /**
   * Which section of the Partners page.
   */
  category: 'development' | 'government' | 'donor' | 'corporate';
  /**
   * The logo on its own, trimmed to its edges, ideally on a transparent background. Do not include a frame or a coloured box.
   */
  logo: number | Media;
  /**
   * Their website, if it should link out.
   */
  url?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Job openings and procurement notices.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "opportunities".
 */
export interface Opportunity {
  id: number;
  title: string;
  /**
   * Which page it appears on.
   */
  kind: 'career' | 'procurement';
  /**
   * The site stops showing it after this date, so old vacancies cannot be applied for by mistake.
   */
  closesAt: string;
  /**
   * e.g. Kamonyi District, or Kigali.
   */
  location?: string | null;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * The full terms of reference or job description, if there is one.
   */
  document?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * People who can sign in and edit the website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Shown in the corner of the editor and on changes.
   */
  name: string;
  /**
   * Administrators can add and remove other staff. Everything else is the same.
   */
  role?: ('editor' | 'admin') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'news';
        value: number | News;
      } | null)
    | ({
        relationTo: 'stories';
        value: number | Story;
      } | null)
    | ({
        relationTo: 'programmes';
        value: number | Programme;
      } | null)
    | ({
        relationTo: 'publications';
        value: number | Publication;
      } | null)
    | ({
        relationTo: 'board';
        value: number | Board;
      } | null)
    | ({
        relationTo: 'partners';
        value: number | Partner;
      } | null)
    | ({
        relationTo: 'opportunities';
        value: number | Opportunity;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  date?: T;
  language?: T;
  photo?: T;
  excerpt?: T;
  body?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stories_select".
 */
export interface StoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  date?: T;
  photo?: T;
  excerpt?: T;
  body?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programmes_select".
 */
export interface ProgrammesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  stage?: T;
  order?: T;
  districts?: T;
  photo?: T;
  summary?: T;
  body?: T;
  components?:
    | T
    | {
        item?: T;
        id?: T;
      };
  runs?: T;
  funder?: T;
  externalUrl?: T;
  unconfirmed?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publications_select".
 */
export interface PublicationsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  date?: T;
  file?: T;
  cover?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "board_select".
 */
export interface BoardSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  order?: T;
  portrait?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  name?: T;
  category?: T;
  logo?: T;
  url?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "opportunities_select".
 */
export interface OpportunitiesSelect<T extends boolean = true> {
  title?: T;
  kind?: T;
  closesAt?: T;
  location?: T;
  body?: T;
  document?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  credit?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        wide?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Address, phone, email, social links, vision and mission.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  email: string;
  /**
   * As displayed, e.g. +250 780 925 908.
   */
  phone: string;
  /**
   * For the tap-to-call link, no spaces: +250780925908.
   */
  phoneHref: string;
  addressLine: string;
  addressDistrict: string;
  addressCountry: string;
  officeHours: string;
  /**
   * Google Maps share link, used by the "Get directions" button.
   */
  mapUrl: string;
  /**
   * From Google Maps: Share > Embed a map > copy the src="..." address only. This pins the exact office rather than guessing from the address.
   */
  mapEmbedUrl: string;
  vision: string;
  /**
   * The phrases to stress in the vision, exactly as they appear in it. Each one is shown at full strength against the words around it.
   */
  visionEmphasis?:
    | {
        phrase: string;
        id?: string | null;
      }[]
    | null;
  mission: string;
  socials?:
    | {
        platform: 'x' | 'linkedin' | 'instagram' | 'facebook' | 'youtube';
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Systems linked in the header strip and footer, e.g. the Sugira Muryango dashboard.
   */
  externalSystems?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The reach figures on the home page and Our Impact.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "impact".
 */
export interface Impact {
  id: number;
  /**
   * Shown in this order. Four is what the design expects.
   */
  figures: {
    /**
     * e.g. Socio-Economic Strengthening.
     */
    label: string;
    /**
     * The number only, no commas or plus sign — the site formats it. Leave blank if MEL has not split this figure out yet; it renders without a number rather than with an invented one.
     */
    value?: number | null;
    caption: string;
    /**
     * Revealed when someone points at the figure.
     */
    areas?:
      | {
          item: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Sits behind the figure on Our Impact.
     */
    photo?: (number | null) | Media;
    id?: string | null;
  }[];
  /**
   * FXBVillage projects delivered to date. Currently 54.
   */
  projectsDelivered: number;
  /**
   * Shown under the figures — where they come from and when they were last updated.
   */
  note?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  email?: T;
  phone?: T;
  phoneHref?: T;
  addressLine?: T;
  addressDistrict?: T;
  addressCountry?: T;
  officeHours?: T;
  mapUrl?: T;
  mapEmbedUrl?: T;
  vision?: T;
  visionEmphasis?:
    | T
    | {
        phrase?: T;
        id?: T;
      };
  mission?: T;
  socials?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  externalSystems?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "impact_select".
 */
export interface ImpactSelect<T extends boolean = true> {
  figures?:
    | T
    | {
        label?: T;
        value?: T;
        caption?: T;
        areas?:
          | T
          | {
              item?: T;
              id?: T;
            };
        photo?: T;
        id?: T;
      };
  projectsDelivered?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}