import data from "./districts.json";

/**
 * Rwanda's 30 districts, as SVG geometry.
 *
 * Generated by `scripts/prepare-districts.mjs` from the National Institute of
 * Statistics of Rwanda's official ADM2 boundaries. Nothing here is drawn by
 * hand: a map of where an organisation works is a factual claim, and an
 * approximated border is a wrong one.
 *
 * The licence requires attribution, which is why `attribution` travels with the
 * geometry rather than living in a component — it must not be possible to
 * render the map without it.
 */
export type District = {
  /** District name, as spelled in the source data. */
  name: string;
  province: Province;
  /** SVG path data, in the shared viewBox. */
  d: string;
  /** Area centroid, for placing a label inside the shape. */
  cx: number;
  cy: number;
  /**
   * Polygon area in SVG units². Used to rank labels: where two names would
   * collide the larger district keeps its label, because it has room for one.
   */
  area: number;
};

export type Province =
  | "City of Kigali"
  | "Southern"
  | "Western"
  | "Northern"
  | "Eastern";

export const districts = data.districts as District[];
export const districtsViewBox = data.viewBox;
export const districtsAttribution = data.attribution;

/** Province order as it reads on a map, north to south rather than alphabetical. */
export const provinces: Province[] = [
  "Northern",
  "Eastern",
  "City of Kigali",
  "Western",
  "Southern",
];
