import manifest from "./board.json";

/**
 * The Board of Directors.
 *
 * Generated by `scripts/prepare-board.mjs` from the portraits FXB supplied,
 * where each filename carries the order, the name and the role. Nothing is
 * transcribed by hand, so the spelling and capitalisation on the site are the
 * ones the organisation delivered — including the upper-case surnames, which
 * mark the family name rather than shout it.
 *
 * Order is the order FXB numbered them: Chairperson, Vice Chairperson,
 * Executive Director, Secretary, then advisors.
 *
 * Unlike the programme photography these are served from the app origin rather
 * than the Bunny pull zone. Eight portraits come to 368KB all told, which is
 * not worth a second hostname, and next/image still resizes and converts them
 * per browser.
 */
export type BoardMember = {
  /** Slug of the name, e.g. `emmanuel-kayitana`. */
  id: string;
  /** As supplied, honorifics and post-nominals included. */
  name: string;
  role: string;
  /** Path under `public/`. */
  src: string;
  width: number;
  height: number;
};

export const board = manifest as BoardMember[];
