import manifest from "./sdg.json";

/**
 * The Sustainable Development Goals the FXBVillage model contributes to.
 *
 * Ten of the seventeen, and the gaps matter: this is the list FXB claims — 1,
 * 2, 3, 4, 5, 6, 8, 13, 16, 17 — not a run from one to seventeen. Each goal
 * carries its own number rather than being re-indexed by position.
 *
 * Generated by `scripts/prepare-sdg.mjs` from the official tiles FXB supplied,
 * so the numbers, the titles and the artwork travel together and cannot drift
 * apart. This replaced a hand-typed list in `fxbvillage.ts` that held the same
 * ten numbers and titles with no images — keeping both would have been two
 * places to edit and one of them silently wrong.
 *
 * The tiles are third-party marks, not brand assets. The UN's guidelines
 * require they be used unaltered: no recolouring, no cropping, no distortion,
 * proportions preserved. That is why they are the one place on this site where
 * colours outside the sanctioned four appear, and why the component that draws
 * them applies no tint, filter or overlay — the same treatment the partner
 * logos get, and for the same reason.
 */
export type Goal = {
  /** The UN's own goal number. Not an index. */
  number: number;
  /** The UN's own title, verbatim. */
  title: string;
  /** Path under `public/`. */
  src: string;
  width: number;
  height: number;
};

export const sdgs = manifest as Goal[];
